name: Deploy to GitHub Pa8ges

# deploy from master
on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # clone repo to vm
    - uses: actions/checkout@v2
    
      # install dependencies
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
        
      # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
        
      # publish static
    - name: Publish .NET Core Project
      working-directory: src
      run: dotnet publish -c:Release -p:GHPages=true -o release --nologo

     # change'/' to '/unitfirstgroup/'
    - name: Change base-tag in index.html from / to unitfirstgroup
      working-directory: src
      run: sed -i 's/<base href="\/" \/>/<base href="\/unitfirstgroup\/" \/>/g' release/wwwroot/index.html
      
     # disable jekyll
    - name: Add .nojekyll file
      working-directory: src
      run: touch release/wwwroot/.nojekyll
      
     # deploy to Github Pages 
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: src/release/wwwroot
        ssh-key: ${{ secrets.DEPLOY_KEY }}